# Best shortcuts
- shift + tab
- %timeit command
    - may not let the line save variables

In [12]:
import pandas as pd

In [13]:
series = pd.Series(['BMW', "Toyota", "Honda"])

In [14]:
series

0       BMW
1    Toyota
2     Honda
dtype: object

In [15]:
colours = pd.Series(["red", "blue", "white"])
colours

0      red
1     blue
2    white
dtype: object

In [16]:
df = pd.DataFrame({"Car make" : series, "Colour": colours})
df

Car make Colour
0      BMW    red
1   Toyota   blue
2    Honda  white

In [17]:
df = pd.read_csv("car-sales.csv")
df.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

# NUMPY

In [18]:
import numpy as np

In [19]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [11]:
type(a1)

numpy.ndarray

In [15]:
ones = np.ones((2,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])